/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NPCDefinition } from './NPCDefinition';
import {
    NPCDefinitionFromJSON,
    NPCDefinitionFromJSONTyped,
    NPCDefinitionToJSON,
} from './NPCDefinition';

/**
 * 
 * @export
 * @interface APINPCData
 */
export interface APINPCData {
    /**
     * 
     * @type {string}
     * @memberof APINPCData
     */
    id: string;
    /**
     * 
     * @type {NPCDefinition}
     * @memberof APINPCData
     */
    definition: NPCDefinition;
    /**
     * 
     * @type {string}
     * @memberof APINPCData
     */
    currentTask: string | null;
}

/**
 * Check if a given object implements the APINPCData interface.
 */
export function instanceOfAPINPCData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "definition" in value;
    isInstance = isInstance && "currentTask" in value;

    return isInstance;
}

export function APINPCDataFromJSON(json: any): APINPCData {
    return APINPCDataFromJSONTyped(json, false);
}

export function APINPCDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): APINPCData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'definition': NPCDefinitionFromJSON(json['definition']),
        'currentTask': json['current_task'],
    };
}

export function APINPCDataToJSON(value?: APINPCData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'definition': NPCDefinitionToJSON(value.definition),
        'current_task': value.currentTask,
    };
}

