/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExerciseCreationABCDE } from './ExerciseCreationABCDE';
import {
    ExerciseCreationABCDEFromJSON,
    ExerciseCreationABCDEFromJSONTyped,
    ExerciseCreationABCDEToJSON,
} from './ExerciseCreationABCDE';
import type { ExerciseCreationVitalSigns } from './ExerciseCreationVitalSigns';
import {
    ExerciseCreationVitalSignsFromJSON,
    ExerciseCreationVitalSignsFromJSONTyped,
    ExerciseCreationVitalSignsToJSON,
} from './ExerciseCreationVitalSigns';

/**
 * 
 * @export
 * @interface ExerciseCreationFutureState
 */
export interface ExerciseCreationFutureState {
    /**
     * 
     * @type {string}
     * @memberof ExerciseCreationFutureState
     */
    events: string;
    /**
     * 
     * @type {ExerciseCreationVitalSigns}
     * @memberof ExerciseCreationFutureState
     */
    vitalSigns: ExerciseCreationVitalSigns;
    /**
     * 
     * @type {ExerciseCreationABCDE}
     * @memberof ExerciseCreationFutureState
     */
    aBCDE: ExerciseCreationABCDE;
}

/**
 * Check if a given object implements the ExerciseCreationFutureState interface.
 */
export function instanceOfExerciseCreationFutureState(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "events" in value;
    isInstance = isInstance && "vitalSigns" in value;
    isInstance = isInstance && "aBCDE" in value;

    return isInstance;
}

export function ExerciseCreationFutureStateFromJSON(json: any): ExerciseCreationFutureState {
    return ExerciseCreationFutureStateFromJSONTyped(json, false);
}

export function ExerciseCreationFutureStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseCreationFutureState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'events': json['events'],
        'vitalSigns': ExerciseCreationVitalSignsFromJSON(json['vitalSigns']),
        'aBCDE': ExerciseCreationABCDEFromJSON(json['ABCDE']),
    };
}

export function ExerciseCreationFutureStateToJSON(value?: ExerciseCreationFutureState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'events': value.events,
        'vitalSigns': ExerciseCreationVitalSignsToJSON(value.vitalSigns),
        'ABCDE': ExerciseCreationABCDEToJSON(value.aBCDE),
    };
}

