/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExerciseCreationPatientBasicInfo } from './ExerciseCreationPatientBasicInfo';
import {
    ExerciseCreationPatientBasicInfoFromJSON,
    ExerciseCreationPatientBasicInfoFromJSONTyped,
    ExerciseCreationPatientBasicInfoToJSON,
} from './ExerciseCreationPatientBasicInfo';

/**
 * 
 * @export
 * @interface ExerciseCreationParams
 */
export interface ExerciseCreationParams {
    /**
     * 
     * @type {ExerciseCreationPatientBasicInfo}
     * @memberof ExerciseCreationParams
     */
    basicInfo: ExerciseCreationPatientBasicInfo;
    /**
     * 
     * @type {string}
     * @memberof ExerciseCreationParams
     */
    exerciseDescription: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseCreationParams
     */
    simulationInstructions: string;
}

/**
 * Check if a given object implements the ExerciseCreationParams interface.
 */
export function instanceOfExerciseCreationParams(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "basicInfo" in value;
    isInstance = isInstance && "exerciseDescription" in value;
    isInstance = isInstance && "simulationInstructions" in value;

    return isInstance;
}

export function ExerciseCreationParamsFromJSON(json: any): ExerciseCreationParams {
    return ExerciseCreationParamsFromJSONTyped(json, false);
}

export function ExerciseCreationParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseCreationParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'basicInfo': ExerciseCreationPatientBasicInfoFromJSON(json['basic_info']),
        'exerciseDescription': json['exerciseDescription'],
        'simulationInstructions': json['simulationInstructions'],
    };
}

export function ExerciseCreationParamsToJSON(value?: ExerciseCreationParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'basic_info': ExerciseCreationPatientBasicInfoToJSON(value.basicInfo),
        'exerciseDescription': value.exerciseDescription,
        'simulationInstructions': value.simulationInstructions,
    };
}

