/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseModel
 */
export interface ExerciseModel {
    /**
     * 
     * @type {string}
     * @memberof ExerciseModel
     */
    exerciseName: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseModel
     */
    exerciseData: string;
    /**
     * 
     * @type {string}
     * @memberof ExerciseModel
     */
    exerciseMetadata: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseModel
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the ExerciseModel interface.
 */
export function instanceOfExerciseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exerciseName" in value;
    isInstance = isInstance && "exerciseData" in value;
    isInstance = isInstance && "exerciseMetadata" in value;
    isInstance = isInstance && "tags" in value;

    return isInstance;
}

export function ExerciseModelFromJSON(json: any): ExerciseModel {
    return ExerciseModelFromJSONTyped(json, false);
}

export function ExerciseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exerciseName': json['exerciseName'],
        'exerciseData': json['exerciseData'],
        'exerciseMetadata': json['exerciseMetadata'],
        'tags': json['tags'],
    };
}

export function ExerciseModelToJSON(value?: ExerciseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exerciseName': value.exerciseName,
        'exerciseData': value.exerciseData,
        'exerciseMetadata': value.exerciseMetadata,
        'tags': value.tags,
    };
}

