/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NPCDefinition
 */
export interface NPCDefinition {
    /**
     * 
     * @type {string}
     * @memberof NPCDefinition
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NPCDefinition
     */
    role: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NPCDefinition
     */
    specialities: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof NPCDefinition
     */
    yearsOfExperience: number;
}

/**
 * Check if a given object implements the NPCDefinition interface.
 */
export function instanceOfNPCDefinition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "specialities" in value;
    isInstance = isInstance && "yearsOfExperience" in value;

    return isInstance;
}

export function NPCDefinitionFromJSON(json: any): NPCDefinition {
    return NPCDefinitionFromJSONTyped(json, false);
}

export function NPCDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NPCDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
        'specialities': json['specialities'],
        'yearsOfExperience': json['years_of_experience'],
    };
}

export function NPCDefinitionToJSON(value?: NPCDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'role': value.role,
        'specialities': value.specialities,
        'years_of_experience': value.yearsOfExperience,
    };
}

