/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatientBasicInfo
 */
export interface PatientBasicInfo {
    /**
     * 
     * @type {string}
     * @memberof PatientBasicInfo
     */
    age: string;
    /**
     * 
     * @type {string}
     * @memberof PatientBasicInfo
     */
    sex: string;
    /**
     * 
     * @type {string}
     * @memberof PatientBasicInfo
     */
    weight: string;
    /**
     * 
     * @type {string}
     * @memberof PatientBasicInfo
     */
    height: string;
}

/**
 * Check if a given object implements the PatientBasicInfo interface.
 */
export function instanceOfPatientBasicInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "age" in value;
    isInstance = isInstance && "sex" in value;
    isInstance = isInstance && "weight" in value;
    isInstance = isInstance && "height" in value;

    return isInstance;
}

export function PatientBasicInfoFromJSON(json: any): PatientBasicInfo {
    return PatientBasicInfoFromJSONTyped(json, false);
}

export function PatientBasicInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientBasicInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'age': json['age'],
        'sex': json['sex'],
        'weight': json['weight'],
        'height': json['height'],
    };
}

export function PatientBasicInfoToJSON(value?: PatientBasicInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'age': value.age,
        'sex': value.sex,
        'weight': value.weight,
        'height': value.height,
    };
}

