/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionData
 */
export interface SessionData {
    /**
     * 
     * @type {string}
     * @memberof SessionData
     */
    sessionId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SessionData
     */
    sidsInSession: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof SessionData
     */
    creationDatetime?: Date;
}

/**
 * Check if a given object implements the SessionData interface.
 */
export function instanceOfSessionData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionId" in value;
    isInstance = isInstance && "sidsInSession" in value;

    return isInstance;
}

export function SessionDataFromJSON(json: any): SessionData {
    return SessionDataFromJSONTyped(json, false);
}

export function SessionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'sidsInSession': json['sids_in_session'],
        'creationDatetime': !exists(json, 'creation_datetime') ? undefined : (new Date(json['creation_datetime'])),
    };
}

export function SessionDataToJSON(value?: SessionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session_id': value.sessionId,
        'sids_in_session': value.sidsInSession,
        'creation_datetime': value.creationDatetime === undefined ? undefined : (value.creationDatetime.toISOString()),
    };
}

