/* eslint-disable */
/**
 * This file was automatically generated by packages/tools/generate_sio_class.py
 * GPT made this, so godspeed and good luck.
 */

import { Socket } from "socket.io";
import {SimUpdateData} from "./sioevents";

export abstract class SIOEventProcessor {
  socket: Socket;
  abstract on_test_event(data: SimUpdateData): void;

  constructor(socket: Socket) {
    this.socket = socket;
    this.socket.on("test_event", (data: SimUpdateData) => this.on_test_event(data));
  }
}