/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = string;
export type Timestamp = string;
export type NpcId = string | null;
export type Message = string;
export type Timestamp1 = string;
export type NpcId1 = string;
export type Id = string;
export type Id1 = string;
export type Name = string;
export type Role = string;
export type Specialities = string[];
export type YearsOfExperience = number;
export type CurrentTask = string | null;
/**
 * The body temperature in degrees Celsius or Fahrenheit
 */
export type Temperature = number;
/**
 * The heart rate in beats per minute
 */
export type HeartRate = number;
/**
 * The number of breaths taken per minute
 */
export type RespiratoryRate = number;
export type Systolic = number;
export type Diastolic = number;
/**
 * The blood glucose level
 */
export type BloodGlucose = number;
/**
 * The oxygen saturation in percentage
 */
export type OxygenSaturation = number;
/**
 * The capillary refill time in seconds
 */
export type CapillaryRefill = number;
export type Timestamp2 = number;
export type NpcName = string;
export type Content = string;
export type Log = CombatLogElement[];
export type Message1 = string;
export type Timestamp3 = string;
export type TargetNpcId = string | null;

export interface ScribeEvents {
  chat_event: ChatEvent;
  chat_message: MessageFromNPC;
  npc_data: API_NPCUpdateData;
  patient_vitals_update: VitalSigns;
  combatlog_update: CombatLogUpdateData;
  __server_on_join_session?: {
    session_id?: {
      [k: string]: unknown;
    };
  };
  __server_on_leave_session?: {};
  __server_on_chat_message?: {
    data?: HumanMessage;
    return?: {
      [k: string]: unknown;
    };
  };
  __server_on_direct_intervention?: {
    function_call?: {
      [k: string]: unknown;
    };
    return?: {
      [k: string]: unknown;
    };
  };
}
export interface ChatEvent {
  event: Event;
  timestamp: Timestamp;
  npc_id?: NpcId;
}
export interface MessageFromNPC {
  message: Message;
  timestamp: Timestamp1;
  npc_id: NpcId1;
}
export interface API_NPCUpdateData {
  id: Id;
  data: API_NPCData;
}
export interface API_NPCData {
  id: Id1;
  definition: NPCDefinition;
  current_task?: CurrentTask;
  [k: string]: unknown;
}
export interface NPCDefinition {
  name: Name;
  role: Role;
  specialities: Specialities;
  years_of_experience: YearsOfExperience;
  [k: string]: unknown;
}
export interface VitalSigns {
  temperature: Temperature;
  heart_rate: HeartRate;
  respiratory_rate: RespiratoryRate;
  /**
   * Blood pressure measurements
   */
  blood_pressure: BloodPressureModel;
  blood_glucose: BloodGlucose;
  oxygen_saturation: OxygenSaturation;
  capillary_refill: CapillaryRefill;
}
export interface BloodPressureModel {
  systolic: Systolic;
  diastolic: Diastolic;
  [k: string]: unknown;
}
export interface CombatLogUpdateData {
  log: Log;
}
export interface CombatLogElement {
  timestamp: Timestamp2;
  npc_name: NpcName;
  content: Content;
  [k: string]: unknown;
}
export interface HumanMessage {
  message: Message1;
  timestamp: Timestamp3;
  target_npc_id?: TargetNpcId;
}
