/* eslint-disable */
/**
* This file was automatically generated by Scribe's codegen tool.
* This class was generated by GPT3.5, so godspeed and good luck.
*/

import { Socket } from 'socket.io-client';

export enum EmitEvent {
	JOIN_SESSION = "join_session",
	LEAVE_SESSION = "leave_session",
	CHAT_MESSAGE = "chat_message",
	DIRECT_INTERVENTION = "direct_intervention",
}

function subscribe(obj: ScribeClient, event: string, callback?: (data: any) => void) {
    if (callback) {
        obj.socket.on(event, (data) => {
            callback.call(obj, data);
        });
    }
}

import { ChatEvent, MessageFromNPC, SIO_ConnectedDevices, SIO_NPCData, ExposedVitalSigns, CombatLogUpdateData, NPCThinking, SIO_TimeUpdate } from "./scribetypes";

export abstract class ScribeClient {
    socket: Socket;
    on_chat_event?(data: ChatEvent): void;
    on_chat_message?(data: MessageFromNPC): void;
    on_device_update?(data: SIO_ConnectedDevices): void;
    on_npc_data?(data: SIO_NPCData): void;
    on_patient_vitals_update?(data: ExposedVitalSigns): void;
    on_combatlog_update?(data: CombatLogUpdateData): void;
    on_npc_thinking_updated?(data: NPCThinking): void;
    on_time_update?(data: SIO_TimeUpdate): void;

    constructor(socket: Socket) {
        this.socket = socket;
        subscribe(this, "chat_event", this.on_chat_event);
        subscribe(this, "chat_message", this.on_chat_message);
        subscribe(this, "device_update", this.on_device_update);
        subscribe(this, "npc_data", this.on_npc_data);
        subscribe(this, "patient_vitals_update", this.on_patient_vitals_update);
        subscribe(this, "combatlog_update", this.on_combatlog_update);
        subscribe(this, "npc_thinking_updated", this.on_npc_thinking_updated);
        subscribe(this, "time_update", this.on_time_update);
    }
}