/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Message = string;
export type Timestamp = string;
export type Sender = string;
export type Timestamp1 = number;
export type Value = number;
export type Name = string;

export interface ScribeEvents {
  chat_message: ChatMessage;
  patient_state: SimUpdateData;
}
export interface ChatMessage {
  message: Message;
  timestamp: Timestamp;
  sender: Sender;
}
export interface SimUpdateData {
  timestamp: Timestamp1;
  value: Value;
  name: Name;
}
